source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.2'

target 'UnityFramework' do
  pod 'OpenSSL-Universal', '~>1.1.1100'
  pod 'RxAtomic', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'Protobuf', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging',:modular_headers => true
  pod 'FirebaseRemoteConfig',:modular_headers => true
  #pod 'Firebase/Auth'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Alamofire', :modular_headers => true  
  pod 'FBSDKCoreKit', '~> 16.0'
  pod 'FBSDKCoreKit_Basics', '~> 16.0'
  pod 'FBSDKGamingServicesKit', '~> 16.0'
  pod 'FBSDKLoginKit', '~> 16.0'
  pod 'FBSDKShareKit', '~> 16.0'
  pod 'Firebase/Analytics', '10.15.0'
  pod 'Firebase/Core', '10.15.0'
  pod 'Firebase/Messaging', '10.15.0'
  pod 'Firebase/RemoteConfig', '10.15.0'
  pod 'FirebaseAnalytics', '10.15.0'
  pod 'FirebaseAnalyticsOnDeviceConversion', '10.19.0'
  
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.2'
  pod 'AppLovinMediationBidMachineAdapter', '3.0.1.0.0'
  pod 'AppLovinMediationByteDanceAdapter', '6.2.0.7.2'
  pod 'AppLovinMediationChartboostAdapter', '9.7.0.2'
  pod 'AppLovinMediationFacebookAdapter', '6.15.2.1'
  pod 'AppLovinMediationFyberAdapter', '8.3.2.1'
  pod 'AppLovinMediationGoogleAdapter', '11.10.0.0'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '11.10.0.0'
  pod 'AppLovinMediationInMobiAdapter', '10.7.5.1'
  pod 'AppLovinMediationIronSourceAdapter', '8.3.0.0.1'
  pod 'AppLovinMediationMintegralAdapter', '7.7.2.0.1'
  pod 'AppLovinMediationMyTargetAdapter', '5.21.8.0'
  pod 'AppLovinMediationSmaatoAdapter', '22.8.4.1'
  pod 'AppLovinMediationTapjoyAdapter', '12.11.1.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.12.2.1'
  pod 'AppLovinMediationVerveAdapter', '3.0.4.1'
  pod 'AppLovinMediationVungleAdapter', '7.4.1.1'
  pod 'AppLovinSDK', '13.0.0'
  pod 'QINGZHOUTPNiOS', '6.3.68'
  pod 'QINGZHOUTPNPangleSDKAdapter', '6.3.68'
  pod 'QINGZHOUTPNAdmobSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNFyberSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNInmobiSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNIronSourceSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNMintegralSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNPubNativeSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNUnityAdsSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNVungleSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNChartboostSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNFacebookSDKAdapter' , '6.3.68'
  pod 'QINGZHOUTPNApplovinSDKAdapter' , '6.3.68'

  pod 'AppsFlyer-AdRevenue', '6.14.3'
  pod 'AppsFlyerFramework', '6.14.3'
end
target 'Unity-iPhone' do
end
